version: '2'
services:
  order:
    container_name: order
    image: docker.wanbochain.com:5000/biz/order:${order_gid}
    restart: on-failure:3
    stop_grace_period: 30s
    environment:
      - serviceName=order
      - container_ip=${host_ip}
      - host_ip=${host_ip}
      - soa_service_timeout=60000
      - JAVA_OPTS=-Dname=order -Dfile.encoding=UTF-8 -Dsun.jun.encoding=UTF-8  -Dio.netty.leakDetectionLevel=advanced
    env_file:
      - .envs/common.env
    volumes:
      - "/data/logs/order:/dapeng-container/logs"
      - "/data/var/fluent/order/:/fluent-bit/db/"
      - "/home/wanbo/wscompose/config/fluent-bit-dapeng.conf:/opt/fluent-bit/etc/fluent-bit.conf"
      - "/data/var/shm:/data/shm"
    ports:
      - "${order_port}:${order_port}"
    extra_hosts:
      - "fluentd:${fluentd_host}"
      - "fluentdStandby:${fluentdStandby_host}"
      - "db-master:${mysql_host_ip}"
      - "soa_zookeeper:${zookeeper_host_ip}"
      - "redis_host:${redis_host_ip}"
    labels:
      - project.source=https://github.com/wanbochain/order.git
#      - project.build-depends.1=http://pms.today36524.td/central-services/supplier.git@@master
      - project.depends=mysql,zookeeper,redis
      - project.owner=WB
      - project.operation=sh buildOrder.sh

#  dapengMesh:
#    container_name: dapengMesh
#    image: docker.today36524.com.cn:5000/basic/dapeng-mesh:2.1.1
#    restart: on-failure:3
#    stop_grace_period: 30s
#    environment:
#      - serviceName=dapengMesh
#      - container_ip=${host_ip}
#      - host_ip=${host_ip}
#      - fluentBitLogPath=/dapeng-mesh/logs/*.log
#      - fluentBitLogPathExclude=/dapeng-mesh/logs/console.log,/dapeng-mesh/logs/fluent*.log,/dapeng-mesh/logs/gc*.log
#      - soa_service_timeout=120000
#      - E_JAVA_OPTS=-Dname=dapengMesh ${soa_jvm_ops} -XX:NewRatio=1 -XX:SurvivorRatio=30 -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom -Dsun.jun.encoding=UTF-8 -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGC -XX:+HeapDumpOnOutOfMemoryError
#    env_file:
#      - .envs/common.env
#    volumes:
#      - "/data/var/fluent/dapeng-mesh/:/fluent-bit/db/"
#      - "/data/logs/dapeng-mesh:/dapeng-mesh/logs"
#    ports:
#      - "8989:9000"
#    extra_hosts:
#      - "fluentd:${fluentd_host}"
#      - "fluentdStandby:${fluentdStandby_host}"
#      - "soa_zookeeper:${zookeeper_host_ip}"
#    labels:
#      - project.source=
#      - project.depends=zookeeper
#      - project.extra=public-image


#  idGenService:
#    container_name: idGenService
#    image: docker.today36524.com.cn:5000/biz/idgen_service:${idGenService_gid}
#    restart: on-failure:3
#    stop_grace_period: 30s
#    environment:
#      - soa_container_port=${soa_port}
#      - soa_container_ip=${host_ip}
#      - container_ip=${host_ip}
#      - host_ip=${host_ip}
#      - E_JAVA_OPTS= -Dname=idGenService ${soa_jvm_ops}
#      - database_encrypt_enable=false
#      - serviceName=idGenService
#      - APM_OPTS=-Dskywalking.agent.application_code=idGenService -Dskywalking.collector.servers=${apm_server} -Dskywalking.logging.level=ERROR -javaagent:/opt/skywalking-agent/skywalking-agent.jar
#    env_file:
#      - .envs/application.env
#      - .envs/common.env
#    volumes:
#      - "/data/logs/dapeng/idgen-services:/dapeng-container/logs"
#      - "/home/today/tscompose/config/fluent-bit-dapeng.conf:/opt/fluent-bit/etc/fluent-bit.conf"
#      - "/data/var/fluent/idGenService/:/fluent-bit/db/"
#      - "/data/var/shm:/data/shm"
#    ports:
#      - "${basic_id_gen_port}:${soa_port}"
#    extra_hosts:
#      - "fluentd:${fluentd_host}"
#      - "fluentdStandby:${fluentdStandby_host}"
#      - "db-master:${mysql_host_ip}"
#      - "soa_zookeeper:${zookeeper_host_ip}"
#    labels:
#      - project.source=http://pms.today36524.td/basic-services/gen_id.git@@master
#      - project.depends=mysql,zookeeper
#      - project.owner=LHZ
#      - project.operation=sh buildIdGen.sh

  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.4.11
    restart: on-failure:3
    environment:
      - LANG=zh_CN.UTF-8
      - TZ=CST-8
      - ZOO_MAX_CLIENT_CNXNS=500
    ports:
      - "${zookeeper_port}:2181"
      - "2888:2888"
      - "3888:3888"
    labels:
      - project.source=
      - project.depends=
      - project.extra=public-image
      - project.owner=LHZ

  mysql:
    container_name: mysql
    image: mariadb:10.2.13
    restart: on-failure:3
    environment:
      - MYSQL_ROOT_PASSWORD=today-36524
      - TZ=CST-8
      - LANG=zh_CN.UTF-8
    volumes:
      - /data/var/mysql/:/var/lib/mysql
      - /data/var/mysql-conf/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    labels:
      - project.source=
      - project.depends=
      - project.extra=public-image
      - project.owner=LJY


  tengine:
    container_name: tengine
    image: docker.today36524.com.cn:5000/basic/tengine:2.0.4
    restart: on-failure:3
    environment:
      - LANG=zh_CN.UTF-8
      - TZ=CST-8
    volumes:
      - /data/config/nginx/conf.d/:/etc/nginx/conf.d/
      - /home/today/tscompose/config/nginx.conf:/etc/nginx/nginx.conf
      - /data/config/nginx/cert/:/etc/nginx/cert/
      - /data/logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    labels:
      - project.source=
      - project.depends=
      - project.extra=public-image
      - project.owner=Ever


  redis:
    container_name: redis
    image: dapengsoa/redis-wzx-alpine:3.2.10
    restart: on-failure:3
    environment:
      - LANG=zh_CN.UTF-8
      - TZ=CST-8
    ports:
      - "6379:6379"
    command: redis-server /etc/redis/redis.conf
    volumes:
      - /home/today/tscompose/config/redis_config:/etc/redis
    labels:
      - project.source=
      - project.depends=
      - project.extra=public-image
      - project.owner=Ever

  canal:
    container_name: canal
    image: docker.today36524.com.cn:5000/today/canal:v1.1.0
    environment:
      - TZ=CST-8
      - LANG=zh_CN.UTF-8
    ports:
      - "${canal_port}:${canal_port}"
      - "11112:11112"
    extra_hosts:
      - "db-master:${mysql_host_ip}"
    volumes:
      - "/data/logs/canal/:/canal-server/logs"
      - "/data/var/canal/instance.properties:/canal-server/conf/today/instance.properties"
    labels:
      - project.source=
      - project.depends=kafka
      - project.extra=public-image
      - project.owner=LHZ

  binlog:
    container_name: binlogService
    image: docker.today36524.com.cn:5000/basic/binlog:stable
    restart: on-failure:3
    environment:
      - TZ=CST-8
      - canal_canalServerIp=${canal_host_ip}
      - canal_canalServerPort=${canal_port}
      - kafka_topic=${binlog_topic}
    extra_hosts:
      - "kafka-host:${kafka_host_ip}"
    volumes:
      - "/data/logs/binlog-service/:/opt/binlog/logs"
    labels:
      - project.source=
      - project.extra=public-image
      - project.depends=mysql,canal,kafka
      - project.owner=LHZ

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.12-2.1.0
    restart: on-failure:3
    ports:
      - "${kafka_port}:${kafka_port}"
      - "9094:9094"
    environment:
      - TZ=CST-8
      - KAFKA_BROKER_ID=2
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_ZOOKEEPER_CONNECT=${zookeeper_host_ip}:2181
      - KAFKA_LOG_DIRS=/kafka/logs
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${kafka_host_ip}:${kafka_port}
      - KAFKA_LISTENERS=PLAINTEXT://:${kafka_port}
    volumes:
      - "/data/logs/kafka-logs/:/kafka/logs"
    labels:
      - project.source=
      - project.extra=public-image
      - project.depends=zookeeper
      - project.owner=LHZ

  fluentd:
    container_name: fluentd
    image: docker.today36524.com.cn:5000/basic/fluentd:v1.2
    restart: on-failure:3
    volumes:
      - /data/var/fluentd/log:/fluentd/log
      - /data/var/fluentd/etc:/fluentd/etc
    environment:
      - LANG=zh_CN.UTF-8
      - TZ=CST-8
    ports:
      - "24224:24224"
    labels:
      - project.source=
      - project.extra=public-image
      - project.depends=
      - project.owner=zhup


